apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parallel-pipeline-
spec:
  arguments:
    parameters:
    - name: url1
      value: gs://ml-pipeline-playground/shakespeare1.txt
    - name: url2
      value: gs://ml-pipeline-playground/shakespeare2.txt
  entrypoint: parallel-pipeline
  serviceAccountName: pipeline-runner
  templates:
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: gcs-download-2-data
            value: '{{inputs.parameters.gcs-download-2-data}}'
          - name: gcs-download-data
            value: '{{inputs.parameters.gcs-download-data}}'
        name: echo-exec
        template: echo-exec
      - arguments:
          parameters:
          - name: execution
            value: '{"inputs": {"gcs-download-2-data": "{{inputs.parameters.gcs-download-2-data}}",
              "gcs-download-data": "{{inputs.parameters.gcs-download-data}}"}, "outputs":
              {}}'
        dependencies:
        - echo-exec
        name: echo-track
        template: echo-track
    inputs:
      parameters:
      - name: gcs-download-2-data
      - name: gcs-download-data
    name: echo
  - container:
      args:
      - 'echo "Text 1: $0"; echo "Text 2: $1"'
      - '{{inputs.parameters.gcs-download-data}}'
      - '{{inputs.parameters.gcs-download-2-data}}'
      command:
      - sh
      - -c
      image: library/bash:4.4.23
    inputs:
      parameters:
      - name: gcs-download-2-data
      - name: gcs-download-data
    name: echo-exec
    outputs:
      artifacts:
      - name: mlpipeline-ui-metadata
        optional: true
        path: /mlpipeline-ui-metadata.json
      - name: mlpipeline-metrics
        optional: true
        path: /mlpipeline-metrics.json
  - container:
      args:
      - track.py
      - '{{inputs.parameters.execution}}'
      image: gcr.io/hongyes-ml/metadata-tool:latest
    inputs:
      parameters:
      - name: execution
    name: echo-track
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: url1
            value: '{{inputs.parameters.url1}}'
        name: gcs-download-exec
        template: gcs-download-exec
      - arguments:
          parameters:
          - name: execution
            value: '{"inputs": {"url1": "{{inputs.parameters.url1}}"}, "outputs":
              {"data": "{{tasks.gcs-download-exec.outputs.parameters.gcs-download-data}}"}}'
        dependencies:
        - gcs-download-exec
        name: gcs-download-track
        template: gcs-download-track
    inputs:
      parameters:
      - name: url1
    name: gcs-download
    outputs:
      parameters:
      - name: gcs-download-data
        valueFrom:
          parameter: '{{tasks.gcs-download-track.outputs.parameters.gcs-download-data}}'
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: url2
            value: '{{inputs.parameters.url2}}'
        name: gcs-download-2-exec
        template: gcs-download-2-exec
      - arguments:
          parameters:
          - name: execution
            value: '{"inputs": {"url2": "{{inputs.parameters.url2}}"}, "outputs":
              {"data": "{{tasks.gcs-download-2-exec.outputs.parameters.gcs-download-2-data}}"}}'
        dependencies:
        - gcs-download-2-exec
        name: gcs-download-2-track
        template: gcs-download-2-track
    inputs:
      parameters:
      - name: url2
    name: gcs-download-2
    outputs:
      parameters:
      - name: gcs-download-2-data
        valueFrom:
          parameter: '{{tasks.gcs-download-2-track.outputs.parameters.gcs-download-2-data}}'
  - container:
      args:
      - gsutil cat $0 | tee $1
      - '{{inputs.parameters.url2}}'
      - /tmp/results.txt
      command:
      - sh
      - -c
      image: google/cloud-sdk:216.0.0
    inputs:
      parameters:
      - name: url2
    name: gcs-download-2-exec
    outputs:
      artifacts:
      - name: mlpipeline-ui-metadata
        optional: true
        path: /mlpipeline-ui-metadata.json
      - name: mlpipeline-metrics
        optional: true
        path: /mlpipeline-metrics.json
      parameters:
      - name: gcs-download-2-data
        valueFrom:
          path: /tmp/results.txt
  - container:
      args:
      - track.py
      - '{{inputs.parameters.execution}}'
      image: gcr.io/hongyes-ml/metadata-tool:latest
    inputs:
      parameters:
      - name: execution
    name: gcs-download-2-track
    outputs:
      parameters:
      - name: gcs-download-2-data
        valueFrom:
          path: /tmp/data
  - container:
      args:
      - gsutil cat $0 | tee $1
      - '{{inputs.parameters.url1}}'
      - /tmp/results.txt
      command:
      - sh
      - -c
      image: google/cloud-sdk:216.0.0
    inputs:
      parameters:
      - name: url1
    name: gcs-download-exec
    outputs:
      artifacts:
      - name: mlpipeline-ui-metadata
        optional: true
        path: /mlpipeline-ui-metadata.json
      - name: mlpipeline-metrics
        optional: true
        path: /mlpipeline-metrics.json
      parameters:
      - name: gcs-download-data
        valueFrom:
          path: /tmp/results.txt
  - container:
      args:
      - track.py
      - '{{inputs.parameters.execution}}'
      image: gcr.io/hongyes-ml/metadata-tool:latest
    inputs:
      parameters:
      - name: execution
    name: gcs-download-track
    outputs:
      parameters:
      - name: gcs-download-data
        valueFrom:
          path: /tmp/data
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: gcs-download-2-data
            value: '{{tasks.gcs-download-2.outputs.parameters.gcs-download-2-data}}'
          - name: gcs-download-data
            value: '{{tasks.gcs-download.outputs.parameters.gcs-download-data}}'
        dependencies:
        - gcs-download
        - gcs-download-2
        name: echo
        template: echo
      - arguments:
          parameters:
          - name: url1
            value: '{{inputs.parameters.url1}}'
        name: gcs-download
        template: gcs-download
      - arguments:
          parameters:
          - name: url2
            value: '{{inputs.parameters.url2}}'
        name: gcs-download-2
        template: gcs-download-2
    inputs:
      parameters:
      - name: url1
      - name: url2
    name: parallel-pipeline
